const request = require("supertest");
const app = require("../index");
const {
  sequelize,
  user: User,
  incident: Incident,
  incidentComment: IncidentComment,
} = require("../models");
const jwt = require("jsonwebtoken");
const { jwtConfig } = require("../config/jwt");

describe("IncidentComment API (JWT Auth)", () => {
  let userToken;
  let otherUserToken; // Token for a different user
  let userId;
  let otherUserId;
  let incidentId;
  let commentId;

  // Runs before all tests
  beforeAll(async () => {
    // 1. Find an existing user for testing or create one
    let user = await User.findOne({
      where: { email: "test_comment_user@example.com" },
    });

    if (!user) {
      user = await User.create({
        firstName: "Test",
        lastName: "User",
        email: "test_comment_user@example.com",
        password: "password123",
        roleId: 1, // Normal user
        dateRegister: new Date(),
      });
    }
    userId = user.id;

    // 2. Generate JWT token for this user
    userToken = jwt.sign(
      { id: user.id, email: user.email, role: "usuario" },
      jwtConfig.secret
    );

    // 3. Create a second user to test permissions
    let otherUser = await User.findOne({
      where: { email: "other_comment_user@example.com" },
    });
    if (!otherUser) {
      otherUser = await User.create({
        firstName: "Other",
        lastName: "User",
        email: "other_comment_user@example.com",
        password: "password123",
        roleId: 1,
        dateRegister: new Date(),
      });
    }
    otherUserId = otherUser.id;
    otherUserToken = jwt.sign(
      { id: otherUser.id, email: otherUser.email, role: "usuario" },
      jwtConfig.secret
    );

    // 4. Find an existing incident
    let incident = await Incident.findOne();

    // If it doesn't exist, try to create one (requires status/severity/type with ID 1 to exist)
    if (!incident) {
      try {
        incident = await Incident.create({
          userId: userId,
          title: "Test Comments Incident",
          description: "Incident created for testing",
          latitude: 40.416775,
          longitude: -3.70379,
          statusId: 1,
          severityId: 1,
          typeId: 1,
          isApproved: true,
        });
      } catch (error) {
        console.error(
          "Could not create a test incident. Make sure to run seeders (npm run db:seed:test) or have master data."
        );
        throw error;
      }
    }
    incidentId = incident.id;
  });

  // Runs after all tests
  afterAll(async () => {
    // Cleanup: Delete the created comment
    if (commentId) {
      await IncidentComment.destroy({ where: { id: commentId } });
    }
    await sequelize.close();
  });

  // --- TESTS ---

  // 1. Create comment (POST)
  test("POST /api/incident-comments - Should create an authenticated comment", async () => {
    const res = await request(app)
      .post("/api/incident-comments")
      .set("Authorization", `Bearer ${userToken}`)
      .send({
        incidentId: incidentId,
        comment: "Comment generated by automated Test",
      });

    expect(res.statusCode).toEqual(201);
    expect(res.body).toHaveProperty("id");
    expect(res.body.comment).toBe("Comment generated by automated Test");
    expect(res.body.userId).toBe(userId);

    // Save ID to verify deletion or subsequent reading if necessary
    commentId = res.body.id;
  });

  // 2. Read incident comments (GET)
  test("GET /api/incident-comments/incident/:id - Should list comments", async () => {
    const res = await request(app)
      .get(`/api/incident-comments/incident/${incidentId}`)
      .set("Authorization", `Bearer ${userToken}`);

    expect(res.statusCode).toEqual(200);
    expect(Array.isArray(res.body)).toBe(true);

    // Verify that our comment is in the list
    const myComment = res.body.find((c) => c.id === commentId);
    expect(myComment).toBeDefined();
    expect(myComment.comment).toBe("Comment generated by automated Test");
  });

  // 3. Validate security (No Token)
  test("POST /api/incident-comments - Should fail if no token (403/401)", async () => {
    const res = await request(app).post("/api/incident-comments").send({
      incidentId: incidentId,
      comment: "Hacking attempt",
    });

    // Depending on middleware, can be 401 or 403
    expect([401, 403]).toContain(res.statusCode);
  });

  // 4. Validate required data
  test("POST /api/incident-comments - Should fail without message or id", async () => {
    const res = await request(app)
      .post("/api/incident-comments")
      .set("Authorization", `Bearer ${userToken}`)
      .send({
        incidentId: incidentId,
      });

    expect(res.statusCode).toEqual(400);
  });

  // 5. Update comment (PUT)
  test("PUT /api/incident-comments/:id - Should update own comment", async () => {
    const res = await request(app)
      .put(`/api/incident-comments/${commentId}`)
      .set("Authorization", `Bearer ${userToken}`)
      .send({
        comment: "Updated comment by owner",
      });

    expect(res.statusCode).toEqual(200);
    expect(res.body.comment).toBe("Updated comment by owner");
  });

  test("PUT /api/incident-comments/:id - Should NOT update other user's comment", async () => {
    const res = await request(app)
      .put(`/api/incident-comments/${commentId}`)
      .set("Authorization", `Bearer ${otherUserToken}`)
      .send({
        comment: "Hacked comment",
      });

    expect(res.statusCode).toEqual(403);
  });

  // 6. Delete comment (DELETE)
  test("DELETE /api/incident-comments/:id - Should NOT delete other user's comment", async () => {
    const res = await request(app)
      .delete(`/api/incident-comments/${commentId}`)
      .set("Authorization", `Bearer ${otherUserToken}`);

    expect(res.statusCode).toEqual(403);
  });

  test("DELETE /api/incident-comments/:id - Should delete own comment", async () => {
    const res = await request(app)
      .delete(`/api/incident-comments/${commentId}`)
      .set("Authorization", `Bearer ${userToken}`);

    expect(res.statusCode).toEqual(200);

    // Verify it's gone
    const check = await IncidentComment.findByPk(commentId);
    expect(check).toBeNull();

    // Clear commentId so afterAll doesn't try to delete it again
    commentId = null;
  });
});
